require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VodcastsController do

  # This should return the minimal set of attributes required to create a valid
  # Vodcast. As you add validations to Vodcast, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VodcastsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vodcasts as @vodcasts" do
      vodcast = Vodcast.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vodcasts).should eq([vodcast])
    end
  end

  describe "GET show" do
    it "assigns the requested vodcast as @vodcast" do
      vodcast = Vodcast.create! valid_attributes
      get :show, {:id => vodcast.to_param}, valid_session
      assigns(:vodcast).should eq(vodcast)
    end
  end

  describe "GET new" do
    it "assigns a new vodcast as @vodcast" do
      get :new, {}, valid_session
      assigns(:vodcast).should be_a_new(Vodcast)
    end
  end

  describe "GET edit" do
    it "assigns the requested vodcast as @vodcast" do
      vodcast = Vodcast.create! valid_attributes
      get :edit, {:id => vodcast.to_param}, valid_session
      assigns(:vodcast).should eq(vodcast)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vodcast" do
        expect {
          post :create, {:vodcast => valid_attributes}, valid_session
        }.to change(Vodcast, :count).by(1)
      end

      it "assigns a newly created vodcast as @vodcast" do
        post :create, {:vodcast => valid_attributes}, valid_session
        assigns(:vodcast).should be_a(Vodcast)
        assigns(:vodcast).should be_persisted
      end

      it "redirects to the created vodcast" do
        post :create, {:vodcast => valid_attributes}, valid_session
        response.should redirect_to(Vodcast.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vodcast as @vodcast" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vodcast.any_instance.stub(:save).and_return(false)
        post :create, {:vodcast => {}}, valid_session
        assigns(:vodcast).should be_a_new(Vodcast)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vodcast.any_instance.stub(:save).and_return(false)
        post :create, {:vodcast => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vodcast" do
        vodcast = Vodcast.create! valid_attributes
        # Assuming there are no other vodcasts in the database, this
        # specifies that the Vodcast created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vodcast.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => vodcast.to_param, :vodcast => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested vodcast as @vodcast" do
        vodcast = Vodcast.create! valid_attributes
        put :update, {:id => vodcast.to_param, :vodcast => valid_attributes}, valid_session
        assigns(:vodcast).should eq(vodcast)
      end

      it "redirects to the vodcast" do
        vodcast = Vodcast.create! valid_attributes
        put :update, {:id => vodcast.to_param, :vodcast => valid_attributes}, valid_session
        response.should redirect_to(vodcast)
      end
    end

    describe "with invalid params" do
      it "assigns the vodcast as @vodcast" do
        vodcast = Vodcast.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vodcast.any_instance.stub(:save).and_return(false)
        put :update, {:id => vodcast.to_param, :vodcast => {}}, valid_session
        assigns(:vodcast).should eq(vodcast)
      end

      it "re-renders the 'edit' template" do
        vodcast = Vodcast.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vodcast.any_instance.stub(:save).and_return(false)
        put :update, {:id => vodcast.to_param, :vodcast => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vodcast" do
      vodcast = Vodcast.create! valid_attributes
      expect {
        delete :destroy, {:id => vodcast.to_param}, valid_session
      }.to change(Vodcast, :count).by(-1)
    end

    it "redirects to the vodcasts list" do
      vodcast = Vodcast.create! valid_attributes
      delete :destroy, {:id => vodcast.to_param}, valid_session
      response.should redirect_to(vodcasts_url)
    end
  end

end
